# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItemsTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemsTemplateWindow(object):
    def setupUi(self, ItemsTemplateWindow):
        ItemsTemplateWindow.setObjectName("ItemsTemplateWindow")
        ItemsTemplateWindow.resize(800, 596)
        self.centralwidget = QtWidgets.QWidget(ItemsTemplateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 780, 446))
        self.scroll_area_widget_contents.setObjectName("scroll_area_widget_contents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scroll_area_widget_contents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scroll_area.setWidget(self.scroll_area_widget_contents)
        self.gridLayout.addWidget(self.scroll_area, 1, 0, 1, 1)
        self.main_page_button = QtWidgets.QPushButton(self.centralwidget)
        self.main_page_button.setObjectName("main_page_button")
        self.gridLayout.addWidget(self.main_page_button, 2, 0, 1, 1)
        self.page_title = QtWidgets.QLabel(self.centralwidget)
        self.page_title.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.page_title.setFont(font)
        self.page_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_title.setAutoFillBackground(False)
        self.page_title.setObjectName("page_title")
        self.gridLayout.addWidget(self.page_title, 0, 0, 1, 1)
        ItemsTemplateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ItemsTemplateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ItemsTemplateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ItemsTemplateWindow)
        self.statusbar.setObjectName("statusbar")
        ItemsTemplateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ItemsTemplateWindow)
        QtCore.QMetaObject.connectSlotsByName(ItemsTemplateWindow)

    def retranslateUi(self, ItemsTemplateWindow):
        _translate = QtCore.QCoreApplication.translate
        ItemsTemplateWindow.setWindowTitle(_translate("ItemsTemplateWindow", "MainWindow"))
        self.main_page_button.setText(_translate("ItemsTemplateWindow", "Back"))
        self.page_title.setText(_translate("ItemsTemplateWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ItemsTemplateWindow = QtWidgets.QMainWindow()
    ui = Ui_ItemsTemplateWindow()
    ui.setupUi(ItemsTemplateWindow)
    ItemsTemplateWindow.show()
    sys.exit(app.exec_())
