# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItemsTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemsTemplateWindow(object):
    def setupUi(self, ItemsTemplateWindow):
        ItemsTemplateWindow.setObjectName("ItemsTemplateWindow")
        ItemsTemplateWindow.resize(800, 596)
        self.centralwidget = QtWidgets.QWidget(ItemsTemplateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_page_button = QtWidgets.QPushButton(self.centralwidget)
        self.main_page_button.setGeometry(QtCore.QRect(20, 520, 131, 23))
        self.main_page_button.setObjectName("main_page_button")
        self.page_title = QtWidgets.QLabel(self.centralwidget)
        self.page_title.setEnabled(True)
        self.page_title.setGeometry(QtCore.QRect(330, 0, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.page_title.setFont(font)
        self.page_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_title.setAutoFillBackground(False)
        self.page_title.setObjectName("page_title")
        self.scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_area.setGeometry(QtCore.QRect(20, 60, 761, 451))
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 759, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area_widger_contents = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.scroll_area_widger_contents.setGeometry(QtCore.QRect(9, 9, 741, 431))
        self.scroll_area_widger_contents.setObjectName("scroll_area_widger_contents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scroll_area_widger_contents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 741, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_layout.setContentsMargins(0, 0, 0, 0)
        self.grid_layout.setObjectName("grid_layout")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        ItemsTemplateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ItemsTemplateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ItemsTemplateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ItemsTemplateWindow)
        self.statusbar.setObjectName("statusbar")
        ItemsTemplateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ItemsTemplateWindow)
        QtCore.QMetaObject.connectSlotsByName(ItemsTemplateWindow)

    def retranslateUi(self, ItemsTemplateWindow):
        _translate = QtCore.QCoreApplication.translate
        ItemsTemplateWindow.setWindowTitle(_translate("ItemsTemplateWindow", "MainWindow"))
        self.main_page_button.setText(_translate("ItemsTemplateWindow", "Back"))
        self.page_title.setText(_translate("ItemsTemplateWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ItemsTemplateWindow = QtWidgets.QMainWindow()
    ui = Ui_ItemsTemplateWindow()
    ui.setupUi(ItemsTemplateWindow)
    ItemsTemplateWindow.show()
    sys.exit(app.exec_())
