# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItemAdded.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemAddedWindow(object):
    def setupUi(self, ItemAddedWindow):
        ItemAddedWindow.setObjectName("ItemAddedWindow")
        ItemAddedWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ItemAddedWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_page_button = QtWidgets.QPushButton(self.centralwidget)
        self.main_page_button.setGeometry(QtCore.QRect(310, 320, 141, 23))
        self.main_page_button.setObjectName("main_page_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 220, 481, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        ItemAddedWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ItemAddedWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ItemAddedWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ItemAddedWindow)
        self.statusbar.setObjectName("statusbar")
        ItemAddedWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ItemAddedWindow)
        QtCore.QMetaObject.connectSlotsByName(ItemAddedWindow)

    def retranslateUi(self, ItemAddedWindow):
        _translate = QtCore.QCoreApplication.translate
        ItemAddedWindow.setWindowTitle(_translate("ItemAddedWindow", "MainWindow"))
        self.main_page_button.setText(_translate("ItemAddedWindow", "Back To Home Page"))
        self.label.setText(_translate("ItemAddedWindow", "Item was added Sucessfuly"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ItemAddedWindow = QtWidgets.QMainWindow()
    ui = Ui_ItemAddedWindow()
    ui.setupUi(ItemAddedWindow)
    ItemAddedWindow.show()
    sys.exit(app.exec_())
