# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ItemsTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemsTemplateWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_page_button = QtWidgets.QPushButton(self.centralwidget)
        self.main_page_button.setGeometry(QtCore.QRect(30, 520, 131, 23))
        self.main_page_button.setObjectName("main_page_button")
        self.picture_label = QtWidgets.QLabel(self.centralwidget)
        self.picture_label.setGeometry(QtCore.QRect(320, 170, 121, 81))
        self.picture_label.setObjectName("picture_label")
        self.page_title = QtWidgets.QLabel(self.centralwidget)
        self.page_title.setEnabled(True)
        self.page_title.setGeometry(QtCore.QRect(260, 40, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.page_title.setFont(font)
        self.page_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page_title.setAutoFillBackground(False)
        self.page_title.setObjectName("page_title")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.main_page_button.setText(_translate("mainWindow", "Back"))
        self.picture_label.setText(_translate("mainWindow", "Picture"))
        self.page_title.setText(_translate("mainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_ItemsTemplateWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
